name: CI
on: [push]

jobs:
  test-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./2-3-4-Exercises
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '23'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test

  test-ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2-3-4-Exercises
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '23'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test